In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.metrics import mean_absolute_percentage_error
from sklearn.preprocessing import StandardScaler

In [11]:
df = pd.read_csv("HousePricePrediction.csv")

In [12]:
df.shape

(2919, 13)

In [13]:
df.head(20)

,Id,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0
5,5,50,RL,14115,Inside,1Fam,5,1993,1995,VinylSd,0.0,796.0,143000.0
6,6,20,RL,10084,Inside,1Fam,5,2004,2005,VinylSd,0.0,1686.0,307000.0
7,7,60,RL,10382,Corner,1Fam,6,1973,1973,HdBoard,32.0,1107.0,200000.0
8,8,50,RM,6120,Inside,1Fam,5,1931,1950,BrkFace,0.0,952.0,129900.0
9,9,190,RL,7420,Corner,2fmCon,6,1939,1950,MetalSd,0.0,991.0,118000.0
10,10,20,RL,11200,Inside,1Fam,5,1965,1965,HdBoard,0.0,1040.0,129500.0
11,11,60,RL,11924,Inside,1Fam,5,2005,2006,WdShing,0.0,1175.0,345000.0
12,12,20,RL,12968,Inside,1Fam,6,1962,1962,HdBoard,0.0,912.0,144000.0
13,13,20,RL,10652,Inside,1Fam,5,2006,2007,VinylSd,0.0,1494.0,279500.0
14,14,20,RL,10920,Corner,1Fam,5,1960,1960,MetalSd,0.0,1253.0,157000.0
15,15,45,RM,6120,Corner,1Fam,8,1929,2001,Wd Sdng,0.0,832.0,132000.0
16,16,20,RL,11241,CulDSac,1Fam,7,1970,1970,Wd Sdng,0.0,1004.0,149000.0
17,17,90,RL,10791,Inside,Duplex,5,1967,1967,MetalSd,0.0,0.0,90000.0
18,18,20,RL,13695,Inside,1Fam,5,2004,2004,VinylSd,0.0,1114.0,159000.0
19,19,20,RL,7560,Inside,1Fam,6,1958,1965,BrkFace,0.0,1029.0,139000.0

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2919 entries, 0 to 2918
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            2919 non-null   int64
 1   MSSubClass    2919 non-null   int64
 2   MSZoning      2915 non-null   object
 3   LotArea       2919 non-null   int64
 4   LotConfig     2919 non-null   object
 5   BldgType      2919 non-null   object
 6   OverallCond   2919 non-null   int64
 7   YearBuilt     2919 non-null   int64
 8   YearRemodAdd  2919 non-null   int64
 9   Exterior1st   2918 non-null   object
 10  BsmtFinSF2    2918 non-null   float64
 11  TotalBsmtSF   2918 non-null   float64
 12  SalePrice     1460 non-null   float64
dtypes: float64(3), int64(6), object(4)
memory usage: 296.6+ KB

In [15]:
df.describe()

,Id,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,SalePrice
count,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2919.000000,2918.000000,2918.000000,1460.000000
mean,1459.000000,57.137718,10168.114080,5.564577,1971.312778,1984.264474,49.582248,1051.777587,180921.195890
std,842.787043,42.517628,7886.996359,1.113131,30.291442,20.894344,169.205611,440.766258,79442.502883
min,0.000000,20.000000,1300.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,34900.000000
25%,729.500000,20.000000,7478.000000,5.000000,1953.500000,1965.000000,0.000000,793.000000,129975.000000
50%,1459.000000,50.000000,9453.000000,5.000000,1973.000000,1993.000000,0.000000,989.500000,163000.000000
75%,2188.500000,70.000000,11570.000000,6.000000,2001.000000,2004.000000,0.000000,1302.000000,214000.000000
max,2918.000000,190.000000,215245.000000,9.000000,2010.000000,2010.000000,1526.000000,6110.000000,755000.000000

In [16]:
#Drop 'ID'
df.drop(['Id'] , axis = 1 , inplace = True)

In [17]:
#Fix null values of 'SalePrice'
df['SalePrice'] = df['SalePrice'].fillna(df['SalePrice'].mean())

In [18]:
# Drop null values
df = df.dropna()

In [19]:
df.isnull().sum()

MSSubClass      0
MSZoning        0
LotArea         0
LotConfig       0
BldgType        0
OverallCond     0
YearBuilt       0
YearRemodAdd    0
Exterior1st     0
BsmtFinSF2      0
TotalBsmtSF     0
SalePrice       0
dtype: int64

In [20]:
df.head()

,MSSubClass,MSZoning,LotArea,LotConfig,BldgType,OverallCond,YearBuilt,YearRemodAdd,Exterior1st,BsmtFinSF2,TotalBsmtSF,SalePrice
0,60,RL,8450,Inside,1Fam,5,2003,2003,VinylSd,0.0,856.0,208500.0
1,20,RL,9600,FR2,1Fam,8,1976,1976,MetalSd,0.0,1262.0,181500.0
2,60,RL,11250,Inside,1Fam,5,2001,2002,VinylSd,0.0,920.0,223500.0
3,70,RL,9550,Corner,1Fam,5,1915,1970,Wd Sdng,0.0,756.0,140000.0
4,60,RL,14260,FR2,1Fam,5,2000,2000,VinylSd,0.0,1145.0,250000.0

In [21]:
# One_Hot_Encoding
cols = ['MSZoning','LotConfig','BldgType','Exterior1st']
df = pd.get_dummies(df,columns = cols , drop_first = True)

In [22]:
df

,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,SalePrice,MSZoning_FV,MSZoning_RH,...,Exterior1st_CemntBd,Exterior1st_HdBoard,Exterior1st_ImStucc,Exterior1st_MetalSd,Exterior1st_Plywood,Exterior1st_Stone,Exterior1st_Stucco,Exterior1st_VinylSd,Exterior1st_Wd Sdng,Exterior1st_WdShing
0,60,8450,5,2003,2003,0.0,856.0,208500.00000,False,False,...,False,False,False,False,False,False,False,True,False,False
1,20,9600,8,1976,1976,0.0,1262.0,181500.00000,False,False,...,False,False,False,True,False,False,False,False,False,False
2,60,11250,5,2001,2002,0.0,920.0,223500.00000,False,False,...,False,False,False,False,False,False,False,True,False,False
3,70,9550,5,1915,1970,0.0,756.0,140000.00000,False,False,...,False,False,False,False,False,False,False,False,True,False
4,60,14260,5,2000,2000,0.0,1145.0,250000.00000,False,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2914,160,1936,7,1970,1970,0.0,546.0,180921.19589,False,False,...,True,False,False,False,False,False,False,False,False,False
2915,160,1894,5,1970,1970,0.0,546.0,180921.19589,False,False,...,True,False,False,False,False,False,False,False,False,False
2916,20,20000,7,1960,1996,0.0,1224.0,180921.19589,False,False,...,False,False,False,False,False,False,False,True,False,False
2917,85,10441,5,1992,1992,0.0,912.0,180921.19589,False,False,...,False,True,False,False,False,False,False,False,False,False
2918,60,9627,5,1993,1994,0.0,996.0,180921.19589,False,False,...,False,True,False,False,False,False,False,False,False,False

In [23]:
# Train Test Split
X = df.drop(['SalePrice'], axis =1)
Y = df['SalePrice']

X_train, X_test, Y_train, Y_test = train_test_split(
    X,Y,test_size=.2,random_state = 0
)

In [24]:
X_train.head(20)

,MSSubClass,LotArea,OverallCond,YearBuilt,YearRemodAdd,BsmtFinSF2,TotalBsmtSF,MSZoning_FV,MSZoning_RH,MSZoning_RL,...,Exterior1st_CemntBd,Exterior1st_HdBoard,Exterior1st_ImStucc,Exterior1st_MetalSd,Exterior1st_Plywood,Exterior1st_Stone,Exterior1st_Stucco,Exterior1st_VinylSd,Exterior1st_Wd Sdng,Exterior1st_WdShing
1453,20,17217,5,2006,2006,0.0,1140.0,False,False,True,...,False,False,False,False,False,False,False,True,False,False
2021,20,19508,5,1974,1974,0.0,1430.0,False,False,True,...,False,True,False,False,False,False,False,False,False,False
188,90,7018,5,1979,1979,0.0,1086.0,False,False,True,...,False,False,False,False,True,False,False,False,False,False
1273,80,11512,7,1959,2006,0.0,1019.0,False,False,True,...,False,False,False,False,True,False,False,False,False,False
1960,20,7560,5,1971,1971,613.0,864.0,False,False,True,...,False,False,False,True,False,False,False,False,False,False
784,75,6300,6,1914,2001,0.0,742.0,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1504,20,8000,5,2002,2002,0.0,1492.0,True,False,False,...,False,False,False,False,False,False,False,True,False,False
2030,120,4538,5,2001,2001,0.0,1310.0,True,False,False,...,False,False,False,False,False,False,False,True,False,False
2070,30,5400,7,1940,2005,0.0,672.0,False,False,True,...,False,False,False,False,False,False,False,True,False,False
2626,120,3701,5,1987,1987,0.0,1191.0,False,False,True,...,False,True,False,False,False,False,False,False,False,False
1051,20,11175,5,2007,2007,0.0,1316.0,False,False,True,...,False,False,False,False,False,False,False,True,False,False
906,20,13501,5,2006,2006,0.0,1623.0,False,False,True,...,False,False,False,False,False,False,False,True,False,False
1042,120,5381,5,2005,2005,0.0,1306.0,False,False,True,...,False,False,False,False,False,False,False,True,False,False
2091,50,7628,6,1940,1985,0.0,801.0,False,False,False,...,False,False,False,True,False,False,False,False,False,False
314,70,9600,7,1925,1990,0.0,728.0,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1122,20,8926,3,1956,1956,0.0,672.0,False,False,True,...,False,False,False,False,False,False,False,False,False,False
37,20,8532,6,1954,1990,0.0,1297.0,False,False,True,...,False,False,False,False,False,False,False,False,True,False
425,60,3378,8,1946,1992,0.0,651.0,False,False,False,...,False,True,False,False,False,False,False,False,False,False
616,60,7861,5,2002,2003,0.0,783.0,False,False,True,...,False,False,False,False,False,False,False,True,False,False
1985,120,3940,5,2004,2004,0.0,1393.0,False,False,False,...,False,False,False,False,False,False,False,True,False,False

In [25]:
# Linear Regression Model
model = LinearRegression()
model.fit(X_train , Y_train)

LinearRegression()

In [26]:
Y_pred = model.predict(X_test)

print("R2 Score : " , r2_score(Y_test, Y_pred))
print("MAE : " , mean_absolute_error(Y_test, Y_pred))
print("RMSE : " , np.sqrt(mean_squared_error(Y_test,Y_pred)))
print("Mean absolute percentage error: " , mean_absolute_percentage_error(Y_test , Y_pred))

R2 Score :  0.37414217961383156
MAE :  30829.93666432242
RMSE :  41138.558702301765
Mean absolute percentage error:  0.18742025463428386

In [27]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = LinearRegression()
model.fit(X_train_scaled, Y_train)

Y_pred = model.predict(X_test_scaled)

In [28]:
print("R2 Score:", r2_score(Y_test, Y_pred))
print("MAE:", mean_absolute_error(Y_test, Y_pred))
print("RMSE:", np.sqrt(mean_squared_error(Y_test, Y_pred)))
print(mean_absolute_percentage_error(Y_test, Y_pred))

R2 Score: 0.3741421796138532
MAE: 30829.93666432187
RMSE: 41138.55870230105
0.18742025463427797